export default [
    // RED CARDS
    { key:"r0", type: 'number', value: '0', color: 'red'},
    { key:"r1", type: 'number', value: '1', color: 'red'},
    { key:"r2", type: 'number', value: '2', color: 'red'},
    { key:"r3", type: 'number', value: '3', color: 'red'},
    { key:"r4", type: 'number', value: '4', color: 'red'},
    { key:"r5", type: 'number', value: '5', color: 'red'},
    { key:"r6", type: 'number', value: '6', color: 'red'},
    { key:"r7", type: 'number', value: '7', color: 'red'},
    { key:"r8", type: 'number', value: '8', color: 'red'},
    { key:"r9", type: 'number', value: '9', color: 'red'},
    // GREEN CARDS
    { key:"g0", type: 'number', value: '0', color: 'green'},
    { key:"g1", type: 'number', value: '1', color: 'green'},
    { key:"g2", type: 'number', value: '2', color: 'green'},
    { key:"g3", type: 'number', value: '3', color: 'green'},
    { key:"g4", type: 'number', value: '4', color: 'green'},
    { key:"g5", type: 'number', value: '5', color: 'green'},
    { key:"g6", type: 'number', value: '6', color: 'green'},
    { key:"g7", type: 'number', value: '7', color: 'green'},
    { key:"g8", type: 'number', value: '8', color: 'green'},
    { key:"g9", type: 'number', value: '9', color: 'green'},
    // BLUE CARDS
    { key:"b0", type: 'number', value: '0', color: 'blue'},
    { key:"b1", type: 'number', value: '1', color: 'blue'},
    { key:"b2", type: 'number', value: '2', color: 'blue'},
    { key:"b3", type: 'number', value: '3', color: 'blue'},
    { key:"b4", type: 'number', value: '4', color: 'blue'},
    { key:"b5", type: 'number', value: '5', color: 'blue'},
    { key:"b6", type: 'number', value: '6', color: 'blue'},
    { key:"b7", type: 'number', value: '7', color: 'blue'},
    { key:"b8", type: 'number', value: '8', color: 'blue'},
    { key:"b9", type: 'number', value: '9', color: 'blue'},
    // YELLOW CARDS
    { key:"y0", type: 'number', value: '0', color: 'yellow'},
    { key:"y1", type: 'number', value: '1', color: 'yellow'},
    { key:"y2", type: 'number', value: '2', color: 'yellow'},
    { key:"y3", type: 'number', value: '3', color: 'yellow'},
    { key:"y4", type: 'number', value: '4', color: 'yellow'},
    { key:"y5", type: 'number', value: '5', color: 'yellow'},
    { key:"y6", type: 'number', value: '6', color: 'yellow'},
    { key:"y7", type: 'number', value: '7', color: 'yellow'},
    { key:"y8", type: 'number', value: '8', color: 'yellow'},
    { key:"y9", type: 'number', value: '9', color: 'yellow'},
]
